### ISSUE TITLE
[Question] Can we work out the peaks for each heartbeat?

### ISSUE THREAD

**Issue by vnl** [kvedala/heart_bpm#1]
Wondering if this can be extended to get Heart Rate Variability by having a longer reading. 
According to a paper, if we accurate manage to measure the time between 2 peaks (the heartbeat). I would be able to put in some algorithms to calculate the HRV.

**Comment by kvedala** [comment]
It was for this reason that I let the algorithm return the timestamp and the measurement value. this way, the developer can use any of the available algorithms ([like these](https://www.coursera.org/lecture/mobile-health-monitoring-systems/peak-detection-algorithms-J8RP0)) to get the peaks and their timestamps to perform various analyses.
